overrides:
  "@types/node": "-"

packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - "@dashevo/protobufjs"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - fsevents
  - microtime
  - protobufjs
  - sharp
