overrides:
  "@vibescraper/website>@types/node": "npm:@types/web@latest"
  "@vibescraper/website>@types/node-legacy": "npm:@types/node@latest"
  "@vibescraper/website>@typescript/lib-dom": "npm:@types/web@latest"

packages:
  - packages/*

onlyBuiltDependencies:
  - "@dashevo/protobufjs"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - fsevents
  - microtime
  - protobufjs
  - sharp
